export const messages = [
  {
    id: "e101",
    subject: "Miss you!",
    body: "Would love to catch up sometimes",
    isRead: false,
    isStarred: false,
    sentAt: 1551133930594,
    removedAt: 1553217535698,
    from: "momo@momo.com",
    to: "omer@gmail.com",
  },
  {
    id: "e102",
    subject: "Meeting Reminder",
    body: "Don’t forget our meeting at 3 PM tomorrow.",
    isRead: true,
    isStarred: false,
    sentAt: 1551220330594,
    removedAt: null,
    from: "manager@company.com",
    to: "omer@gmail.com",
  },
  {
    id: "e103",
    subject: "Project Update",
    body: "The project deadline has been extended.",
    isRead: false,
    isStarred: true,
    sentAt: 1551306730594,
    removedAt: null,
    from: "teamlead@company.com",
    to: "omer@gmail.com",
  },
  {
    id: "e104",
    subject: "Vacation Plans",
    body: "Let’s plan our vacation for next month.",
    isRead: true,
    isStarred: false,
    sentAt: 1551393130594,
    removedAt: 1553217532187,
    from: "omer@gmail.com",
    to: "you@example.com",
  },
  {
    id: "e105",
    subject: "Invoice Attached",
    body: "Please find the attached invoice for your records.",
    isRead: false,
    isStarred: false,
    sentAt: 1551479530594,
    removedAt: null,
    from: "omer@gmail.com",
    to: "client@company.com",
  },
  {
    id: "e106",
    subject: "Congratulations!",
    body: "Congratulations on your recent achievement!",
    isRead: true,
    isStarred: true,
    sentAt: 1551565930594,
    removedAt: null,
    from: "omer@gmail.com",
    to: "employee@company.com",
  },
  {
    id: "e107",
    subject: "Product Launch",
    body: "We are excited to announce the launch of our new product.",
    isRead: false,
    isStarred: false,
    sentAt: 1551652330594,
    removedAt: null,
    from: "marketing@company.com",
    to: "omer@gmail.com",
  },
  {
    id: "e108",
    subject: "Feedback Request",
    body: "We value your feedback on our recent service.",
    isRead: false,
    isStarred: true,
    sentAt: 1551738730594,
    removedAt: null,
    from: "support@company.com",
    to: "omer@gmail.com",
  },
  {
    id: "e109",
    subject: "Weekly Report",
    body: "Here is the weekly report for your review.",
    isRead: true,
    isStarred: false,
    sentAt: 1551825130594,
    removedAt: 1553217536789,
    from: "omer@gmail.com",
    to: "manager@company.com",
  },
  {
    id: "e110",
    subject: "Server Maintenance",
    body: "Scheduled server maintenance will occur this weekend.",
    isRead: false,
    isStarred: false,
    sentAt: 1551911530594,
    removedAt: null,
    from: "it@company.com",
    to: "omer@gmail.com",
  },
  {
    id: "e111",
    subject: "Welcome Aboard",
    body: "Welcome to the team! We are glad to have you with us.",
    isRead: true,
    isStarred: false,
    sentAt: 1551997930594,
    removedAt: 1553217533456,
    from: "omer@gmail.com",
    to: "newhire@company.com",
  },
  {
    id: "e112",
    subject: "Reminder: Deadline Approaching",
    body: "The deadline for the report submission is approaching.",
    isRead: false,
    isStarred: false,
    sentAt: 1552084330594,
    removedAt: null,
    from: "omer@gmail.com",
    to: "team@company.com",
  },
  {
    id: "e113",
    subject: "Networking Event",
    body: "Join us for a networking event next week.",
    isRead: true,
    isStarred: true,
    sentAt: 1552170730594,
    removedAt: null,
    from: "events@company.com",
    to: "omer@gmail.com",
  },
  {
    id: "e114",
    subject: "System Update",
    body: "A new system update is available.",
    isRead: false,
    isStarred: false,
    sentAt: 1552257130594,
    removedAt: null,
    from: "omer@gmail.com",
    to: "all@company.com",
  },
  {
    id: "e115",
    subject: "Appointment Confirmation",
    body: "Your appointment is confirmed for tomorrow.",
    isRead: true,
    isStarred: false,
    sentAt: 1552343530594,
    removedAt: null,
    from: "appointments@company.com",
    to: "omer@gmail.com",
  },
  {
    id: "e116",
    subject: "Survey Participation",
    body: "Please participate in our customer satisfaction survey.",
    isRead: false,
    isStarred: true,
    sentAt: 1552429930594,
    removedAt: null,
    from: "omer@gmail.com",
    to: "customers@company.com",
  },
  {
    id: "e117",
    subject: "Office Closure",
    body: "The office will be closed for the holidays.",
    isRead: false,
    isStarred: false,
    sentAt: 1552516330594,
    removedAt: null,
    from: "omer@gmail.com",
    to: "all@company.com",
  },
  {
    id: "e118",
    subject: "New Policy",
    body: "A new company policy has been implemented.",
    isRead: true,
    isStarred: false,
    sentAt: 1552602730594,
    removedAt: null,
    from: "policy@company.com",
    to: "omer@gmail.com",
  },
  {
    id: "e119",
    subject: "Job Application Received",
    body: "We have received your job application.",
    isRead: true,
    isStarred: false,
    sentAt: 1552689130594,
    removedAt: null,
    from: "omer@gmail.com",
    to: "applicant@company.com",
  },
  {
    id: "e120",
    subject: "Document Submission",
    body: "Please submit the required documents by the end of the week.",
    isRead: false,
    isStarred: false,
    sentAt: 1552775530594,
    removedAt: null,
    from: "admin@company.com",
    to: "omer@gmail.com",
  },
  {
    id: "e121",
    subject: "System Downtime Notice",
    body: "There will be a scheduled downtime for system maintenance.",
    isRead: false,
    isStarred: true,
    sentAt: 1552861930594,
    removedAt: null,
    from: "omer@gmail.com",
    to: "all@company.com",
  },
  {
    id: "e122",
    subject: "Security Update",
    body: "Please update your security settings as soon as possible.",
    isRead: true,
    isStarred: false,
    sentAt: 1552948330594,
    removedAt: null,
    from: "security@company.com",
    to: "omer@gmail.com",
  },
  {
    id: "e123",
    subject: "Annual Review",
    body: "It’s time for your annual performance review.",
    isRead: false,
    isStarred: false,
    sentAt: 1553034730594,
    removedAt: null,
    from: "hr@company.com",
    to: "omer@gmail.com",
  },
  {
    id: "e124",
    subject: "Webinar Invitation",
    body: "You’re invited to our upcoming webinar.",
    isRead: false,
    isStarred: true,
    sentAt: 1553121130594,
    removedAt: null,
    from: "omer@gmail.com",
    to: "contacts@company.com",
  },
  {
    id: "e125",
    subject: "Thank You!",
    body: "Thank you for your recent purchase!",
    isRead: true,
    isStarred: false,
    sentAt: 1553207530594,
    removedAt: null,
    from: "sales@company.com",
    to: "omer@gmail.com",
  },
];

export const loggedinUser = {
  email: "omer@gmail.com",
  fullname: "Mahatma Appsus",
};
